### ISSUE TITLE
Hello stereobooster, I think I found a workaround

### ISSUE THREAD

**Issue by zh0uquan** [stereobooster/create-react-app-map-gl#1]
Hey stereobooster, I also wanted to do a project to use both `creat-react-app` and `react-map-gl`, I did encounter the same issue you have, that's why I am here. I just tried another mapbox react wrapper [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl). And I booted up an initial project...maybe you can also try it

**Comment by stereobooster** [comment]
Does it tries to look take approach of [Controlled Components](https://facebook.github.io/react/docs/forms.html)? E.g. HTML `<input>` is stateful, it is can itself respond to events (keyboard, for example) without React (Flux) data flow, but react folks managed to make input look like it is standard React component.

**Comment by zh0uquan** [comment]
I don't quite get your question, but if you mean is it possible using react wrapper to control the original mapbox-gl, I guess the answer is yes. just check his demos http://alex3165.github.io/react-mapbox-gl/

**Comment by stereobooster** [comment]
> I don't quite get your question, but if you mean is it possible using react wrapper to control the original mapbox-gl

No. Read about [Controlled Components](https://facebook.github.io/react/docs/forms.html).

By default html (pure html, no react) input can handle it's events by itself, you do not need to write JS code. 

But in React you need to handle `input` events for it to update state:

```js
  handleChange(event) {
    this.setState({value: event.target.value});
  }
```

**Comment by zh0uquan** [comment]
ah.ok. I got what you are saying now. but it is out of my scope currently now, I just wanna a easy boilerplate using mapbox and react.

**Comment by stereobooster** [comment]
Well at least Marker/Popup can be done right way https://github.com/alex3165/react-mapbox-gl/pull/207/commits/50fca94af6ec2b8762846110b2be2cceb627205d

**Comment by zh0uquan** [comment]
awesome!

**Comment by stereobooster** [comment]
Welp https://github.com/alex3165/react-mapbox-gl/issues/231 😨
